### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by techtonik** [DrZugrik/Tree-of-Technology--ToT-#4]
Is there an example how it looks like currently?

**Comment by DrZugrik** [comment]
Sorry, no. I think it will be my pet-project, but now I have't any time to work about it. Maybe some latter I finished it, but not soon. (P.s. sorry, eanglish is not my native language =) )

**Comment by DrZugrik** [comment]
If you can help us to make it, please, we're (me and my frien) will glad to anjoy you to this project =)

**Comment by techtonik** [comment]
Well, without any pictures it is hard to estimate its value to jump in. =)
